let number = 555;
console.log(typeof number,number);
let string = 'vor v zakone';
console.log(typeof string, string);
let boolean = false;
console.log(typeof boolean,boolean);
let ad = undefined;
console.log(typeof undefined,undefined);
let api = Symbol('Olof');
console.log(typeof api,api);